name: PR Deploy
run-name: Deploy PR-${{ github.event.inputs.pr-number }}

env:
  ACRONYM: chefs

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: Pull request number
        required: true
        type: string

jobs:
  set-vars:
    name: Set variables
    runs-on: ubuntu-latest
    steps:
      - name: Setting variables
        run: |
          echo ${{ github.sha }}
          echo ${{ github.event.pull_request.head.sha }}
